version: '3.8'

services:
  expo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-recording-expo
    ports:
      - "19000:19000"  # Expo DevTools
      - "19001:19001"  # Expo DevTools websocket
      - "19002:19002"  # Expo DevTools websocket
      - "8081:8081"    # Metro bundler
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    networks:
      - expo-network

networks:
  expo-network:
    driver: bridge

volumes:
  node_modules: